mean_bias_a:
  x: 0.049725549309
  y: 0.280722422325
  z: -9.806383392926
mean_bias_g:
  x: -0.000007296495
  y: -0.000147732137
  z: 0.000591663048
init_ecef:
  #x: 859112.684900000
  x: 859154.069500000
  #y: -4836240.899300000
  y: -4836304.21640000
  #z: 4055467.61860000
  z: 4055377.54750000
init_llh:
  # #x: 0.6934756603499
  # x: 0.6934577813787  #t9
  # #y: -1.3949896896546
  # y: -1.3949836488915  #t9
  # z: 338.9617659955771
  # z: 334.8967113304774  #t9
  # x : 0.6934579636246 #t10
  x : 0.6934573366252 #t11
  # y : -1.3949838421638 #t10
  y : -1.3949832256356 #t11
  # z : 334.9922333794028 #t10
  z : 334.7879310626782 #t11
init_att:
  x: 0.0
  y: 0.0
  #z: 3.220132469929538
  # z: 5.562218882001595 #t9
  # z : 5.4536884913 #t10
  z : 5.5554896681 #t11
  # z: 3.220132469929538
  # z: 3.3
