topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 100
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
